---
title: "Text as Data Basics"
author: "PLSC 21510/31510"
date: "Fall 2022"
output:
  xaringan::moon_reader:
    css: ["default",  "rladies", "rladies-fonts", "libs/rt.css"]
    lib_dir: libs
    nature:
      highlightStyle: github
      highlightLines: true
      countIncrementalSlides: false
      
---
## Why Text as Data

* We care about language.
* Social scientists have always used texts as data. 
* There are costs to large-scale text analysis.
* Computers can lower these costs.


--
#### TAD in Social Science

* Political speeches and deliberations $\leadsto$ internal political workings of governments.
* Electoral manifestos $\leadsto$ parties, political systems, election shifts.
* Newspapers $\leadsto$ media attention and political events.
* Blogs and social media $\leadsto$  public opinion and communication.


---
## Acquiring texts: Sources

#### Where to get texts:
* Online databases, e.g. LexisNexis, Comparative Manifesto Project 
* Websites (Scraping, APIs)
* Archives (High-quality scanner + optical character recognition)

#### Sources we’ll be analyzing:
* Monographs (Machiavelli’s Prince, British Fiction) 
* News Articles (about women around the world) 
* Song Lyrics (Taylor Swift’s Catalog)
* Speeches and Press Releases (by US politicians)

---
### 4 Principles of Computational Text Analysis

#### From Grimmer and Stewart (2013)

1. All Quantitative Models of Language Are Wrong – But Some Are Useful.
2. Quantitative methods for text amplify resources and augment humans.
3. There is no globally best method for automated text analysis. 
4. Validate, Validate, Validate.

#### Ask yourself: If you had unlimited time and an army of RAs, could you complete the job manually? 

* Better yet, could you write a process manual that another researcher could follow, start to finish, to produce the desired result?
* If not, you may need to think more carefully about what you’re hoping to accomplish with the relevant texts.

---
class: center, middle, inverse, title-slide

# Preparing a Corpus

---
## Preparing a corpus

A .accent[corpus] (pl: .accent[corpora]) is a collection of texts, usually stored electronically, and from which we perform our analysis. 

- A corpus might be a collection of news articles from Reuters or the published works of Shakespeare.

<br />


--
Within each corpus we will have separate articles, stories, volumes, each treated as a separate entity or record. Each unit is called a .accent[document] 

- What defines a document will vary depending on the research context.


---
## Digitization

#### Goal: machine readable text

* Store corpus as plain text (e.g. `.txt`, `.csv`), removing unnecessary formatting.

--
* Plain text is .accent[encoded] in different ways. .red[`UTF-8`] is best. 

--
* Leave Excel behind.

--
* Corpora have .accent[data] (the text) and .accent[metadata] (e.g. author, date, publication)

--
* Directory of `.txt`’s or a "tidy" dataset.



???

The same character can be encoded in multiple ways, and default encodings vary across computers and operating systems. For instance, UTF-8 encodes each character using as little as 8 bits of memory, whereas UTF-16 uses at little as 16 bits. Both methods of encoding are variable, meaning they use smaller or larger amounts of memory as needed to store a character. As an example, the character `A` is encoded in UTF-8 as 01000001 and in UTF-16 as 0000000001000001.

CSVs can be tricky, because text data often contain commas and line breaks that introduce parsing er-rors. In our experience, Excel does not handle text-heavy CSVs properly. We recommend that research-ers limit their interaction with corpus-CSVs to R or plain-text editors.

---
## Storing and structuring a corpus



My preferred structure: Each document a row, one column for text, and other columns for metadata. 

Save this table as a delimited plain text file, such as comma separated values.

.scriptsize[
| UID | date | author | title | text |
|---|---|---|---|---|
| 1 | 19-10-2020 | Chris Morris | What does 'no-deal' Australia-style Brexit mean? | Remember how this time last year we were talking about a no-deal Brexit? Well, it's back….Remember how this time last year we were talking about a no-deal Brexit? Well, it's back…. |
| 2 | 08-10-2020 | Andrew Walker | WTO to name first female boss as shortlist narrows | The selection of a new director general of the World Trade Organisation (WTO) is entering its final stage…. |
| 3 | 17-07-2020 | Nicholas Watt | Coronavirus to cause 'nightmare' economic crisis | Coronavirus will lead to a worldwide economic downturn somewhere between a "bad dream and worst nightmare", former cabinet minister Liam Fox has warned… |
]


